name: clang-tidy check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  formatting-check:
    name: Linter Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clang-tidy review
        uses: ZedThree/clang-tidy-review@v0.7.0

