name: Clang Formatting and Linter check.

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  formatting-check:
    name: Formatting and Linter Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check.
        uses: jidicula/clang-format-action@v3.4.0
        with:
          clang-format-version: '10'
