name: ros-ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  master-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - melodic
          - noetic
        include:
          - docker_image: ubuntu:bionic
            ros_distribution: melodic
            ros_version: 1
          - docker_image: ubuntu:focal
            ros_distribution: noetic
            ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup overlay workspace
        run: mkdir -p ros_ws/src
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: mosaic_gnss_driver
          target-ros1-distro: ${{ matrix.ros_distribution }}
#      - name: cd
#        run: bash -c 'cd ros_ws && ls && echo;cd src && ls && echo; cd * && ls && echo; cd mosaic_gnss_driver && ls && echo'
      - name: Generate CMake compile_commands.json
        run: bash -c "source /opt/ros/${{ matrix.ros_distribution }}/setup.sh && cd ros_ws/src/*/mosaic_gnss_driver && cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
      - name: mv stuff
        run: ln -sf /github/workspace ros_ws/src/*/mosaic_gnss_driver
      - name: Run clang-tidy linter check.
        uses: ZedThree/clang-tidy-review@v0.7.0
        with:
          build_dir: "ros_ws/src/*/mosaic_gnss_driver"
